version: "3"

services:
  frontend:
    container_name: bezkoder-frontend
    build:
      context: ./react-crud-web-api/
      dockerfile: Dockerfile
      args:
        - API_HOST=localhost
        - API_PORT=8080
    ports:
      - $FE_PORT:80
    depends_on:
      - backend

  backend:
    container_name: bezkoder-backend
    build:
      context: ./node-express-mongodb/
      dockerfile: Dockerfile
    ports:
      - $BE_PORT:8080
    environment:
      - PORT=8080
      - DB_HOST=mongodb
      - DB_PORT=27017
    depends_on:
      - mongodb

  mongodb:
    container_name: bezkoder-mongodb
    image: mongo:4.4
    ports:
      - $DB_PORT:27017
    volumes:
      - ./data:/data/db
